### ISSUE TITLE
広告掲載のご相談

### ISSUE THREAD

**Issue by yuta090** [autologie/walk30m#7]
始めまして。私採用関係のサービスを展開しております、アルカラ株式会社の高橋と申します。

以前から貴社のサービスを活用させて頂いておりまして、クライアントへのプレゼンにて非常に助かっております。
今回、差し出がましいお話しなのですが、広告掲載を御社にお願い出来ないかと思いましてご連絡させて頂きました。

弊社HPは
http://alcara.biz/
当サービスはWEBスタートパックと申しまして、資料は↓にございます。
http://alcara.biz/webstartpack.pdf
採用難易度の高い企業様や、大手企業様を中心にご利用を頂いておりまして、こちらのサービスのLPを遷移先として広告のご出稿が出来ないかのご相談でございます。

掲載につきましてはCL課金ではなく純広にてご提案させて頂きたく思うのですが、ご掲載にあたっての金額面や掲載位置などご相談させて頂くことは可能でしょうか？
もしよろしければご連絡を頂ければ幸いです。

当方の連絡先は
03-4405-5110（担当高橋）
t@alcara.biz
でございます。お忙しい中恐縮ですが、ご連絡お待ち申し上げております。
※先ほど心ばかりではございますが0.01BTCをご送金させて頂きました。

**Comment by autologie** [comment]
確認が遅くなってすみません。
後ほどメールにて連絡させていただきます。
